import { SalesRepresentative, SalesRepSpecialization, SalesRepStatus } from './crm.types';

export const DEFAULT_SALES_REPRESENTATIVES: Array<Omit<SalesRepresentative, 'id' | 'createdAt' | 'updatedAt'>> = [
  {
    userId: 'u_priya',
    name: 'Priya Sharma',
    email: 'priya.sharma@nationalinteriors.in',
    phone: '+91 98450 12345',
    specialization: 'LUXURY_RESIDENTIAL' as SalesRepSpecialization,
    monthlyTarget: 400000000,
    achievedRevenue: 345000000,
    activeLeadsCount: 8,
    maxCapacity: 12,
    wonDealsCount: 14,
    conversionRate: 38.2,
    status: 'ACTIVE' as SalesRepStatus,
  },
  {
    userId: 'u_arjun',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@nationalinteriors.in',
    phone: '+91 98451 23456',
    specialization: 'COMMERCIAL_OFFICE' as SalesRepSpecialization,
    monthlyTarget: 350000000,
    achievedRevenue: 280000000,
    activeLeadsCount: 6,
    maxCapacity: 10,
    wonDealsCount: 11,
    conversionRate: 35.0,
    status: 'ACTIVE' as SalesRepStatus,
  },
  {
    userId: 'u_vikram',
    name: 'Vikram Patel',
    email: 'vikram.patel@nationalinteriors.in',
    phone: '+91 98452 34567',
    specialization: 'BESPOKE_FURNITURE' as SalesRepSpecialization,
    monthlyTarget: 450000000,
    achievedRevenue: 392000000,
    activeLeadsCount: 9,
    maxCapacity: 12,
    wonDealsCount: 16,
    conversionRate: 41.5,
    status: 'ACTIVE' as SalesRepStatus,
  },
];
