const mongoose = require('mongoose');

const uri = process.env.MONGODB_URI || 'mongodb+srv://Nationalinteriors_app:Niwali8174%23@cluster0.w1hyrzh.mongodb.net/nfi_dev?appName=Cluster0';

async function seed() {
  console.log('Connecting to MongoDB...');
  await mongoose.connect(uri);
  const db = mongoose.connection.db;

  console.log('Fetching or creating categories...');
  const categoryDefs = [
    { name: 'Living Room', slug: 'living-room', description: 'Handcrafted luxury sofas, coffee tables, and credenzas for bespoke living.' },
    { name: 'Sofas', slug: 'sofas', description: 'Opulent plush velvet, top-grain leather, and hand-carved solid wood sofas.' },
    { name: 'Dining', slug: 'dining', description: 'Artisanal dining tables, upholstered chairs, and statement sideboards.' },
    { name: 'Bedroom', slug: 'bedroom', description: 'Heirloom rosewood bedsteads, fluted nightstands, and custom wardrobes.' },
    { name: 'Office', slug: 'office', description: 'Architectural executive desks, ergonomic swivel armchairs, and bookcases.' },
    { name: 'Outdoor', slug: 'outdoor', description: 'Weathered teak loungers and patio furniture built for timeless durability.' },
  ];

  const categoryMap = {};

  for (const cat of categoryDefs) {
    let doc = await db.collection('categories').findOne({ slug: cat.slug, isDeleted: false });
    if (!doc) {
      const res = await db.collection('categories').insertOne({
        _id: new mongoose.Types.ObjectId(),
        name: cat.name,
        slug: cat.slug,
        description: cat.description,
        parentId: null,
        path: cat.slug,
        level: 0,
        imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
        isActive: true,
        isDeleted: false,
        displayOrder: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      categoryMap[cat.slug] = res.insertedId;
      console.log(`Created category: ${cat.name} (${res.insertedId})`);
    } else {
      categoryMap[cat.slug] = doc._id;
      console.log(`Found category: ${cat.name} (${doc._id})`);
    }
  }

  const products = [
    {
      name: 'Royal Teak 8-Seater Dining Table',
      slug: 'royal-teak-8-seater-dining-table',
      sku: 'NFI-DIN-001',
      brand: 'National Furniture & Interiors',
      categorySlug: 'dining',
      description: 'Masterfully crafted from seasoned grade-A Burma teak wood. Finished with natural hand-rubbed Danish oil to highlight the rich golden honey grain.',
      shortDescription: 'Solid Burma teak 8-seater dining table with brass inlays.',
      material: 'Solid Teak Wood',
      primaryMaterial: 'Burma Teak',
      frameMaterial: 'Teak',
      finishes: ['Natural Teak Oil', 'Warm Walnut', 'Smoked Espresso'],
      colors: ['Golden Teak', 'Dark Walnut'],
      dimensions: { length: 240, width: 100, height: 76, unit: 'cm' },
      weight: 85,
      careInstructions: 'Dust with a soft dry cloth. Apply beeswax polish annually to maintain natural luster.',
      warranty: { summary: '10 Years Structural Warranty', periodMonths: 120, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80', publicId: 'dining-1', isPrimary: true, altText: 'Royal Teak Dining Table Hero' },
        { url: 'https://images.unsplash.com/photo-1577140917170-285929fb55b7?auto=format&fit=crop&w=1200&q=80', publicId: 'dining-2', isPrimary: false, altText: 'Wood Joinery Close-up' },
      ],
      basePrice: { amount: 8500000, currency: 'INR' },
      mrp: { amount: 10500000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.9,
      ratingsCount: 24,
      tags: ['dining', 'teak', 'table', 'luxury', 'artisan', 'solid wood'],
      isFeatured: true,
      isBestSeller: true,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Maharaja Hand-Carved Velvet Sofa',
      slug: 'maharaja-hand-carved-velvet-sofa',
      sku: 'NFI-LIV-002',
      brand: 'National Furniture & Interiors',
      categorySlug: 'sofas',
      description: 'An ode to royal Indian heritage. Upholstered in high-density jewel emerald velvet with fluted hand-carved solid rosewood trim and gold leaf highlights.',
      shortDescription: 'Opulent 3-seater velvet sofa with solid rosewood carving.',
      material: 'Royal Velvet & Rosewood Frame',
      primaryMaterial: 'Cotton Velvet',
      frameMaterial: 'Indian Rosewood',
      finishes: ['Royal Emerald', 'Midnight Sapphire', 'Imperial Ochre'],
      colors: ['Emerald Green', 'Deep Sapphire'],
      dimensions: { length: 220, width: 95, height: 88, unit: 'cm' },
      weight: 65,
      careInstructions: 'Professional velvet dry clean only. Vacuum gently with soft brush attachment.',
      warranty: { summary: '5 Years Frame & Foam Warranty', periodMonths: 60, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', publicId: 'sofa-1', isPrimary: true, altText: 'Maharaja Velvet Sofa Front View' },
        { url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', publicId: 'sofa-2', isPrimary: false, altText: 'Sofa Cushion Fabric Detail' },
      ],
      basePrice: { amount: 12000000, currency: 'INR' },
      mrp: { amount: 14500000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 5.0,
      ratingsCount: 31,
      tags: ['sofa', 'living room', 'velvet', 'emerald', 'luxury', 'rosewood'],
      isFeatured: true,
      isBestSeller: true,
      productType: 'MADE_TO_ORDER',
      status: 'PUBLISHED',
    },
    {
      name: 'Scandinavian White Oak Credenza',
      slug: 'scandinavian-white-oak-credenza',
      sku: 'NFI-LIV-003',
      brand: 'National Furniture & Interiors',
      categorySlug: 'living-room',
      description: 'Clean architectural lines meeting Nordic minimalism. Engineered with solid European white oak and soft-close concealed German Blum hinges.',
      shortDescription: 'Modern white oak sideboard credenza with soft-close doors.',
      material: 'White Oak Wood',
      primaryMaterial: 'European Oak',
      frameMaterial: 'Oak',
      finishes: ['Natural White Oak', 'Muted Grey Oak'],
      colors: ['Light Oak', 'Muted Grey'],
      dimensions: { length: 180, width: 45, height: 75, unit: 'cm' },
      weight: 58,
      careInstructions: 'Wipe clean with a microfiber cloth dampened with mild soapy water.',
      warranty: { summary: '5 Years Manufacturer Warranty', periodMonths: 60, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', publicId: 'credenza-1', isPrimary: true, altText: 'White Oak Credenza' },
        { url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', publicId: 'credenza-2', isPrimary: false, altText: 'Oak Wood Grain Texture' },
      ],
      basePrice: { amount: 6200000, currency: 'INR' },
      mrp: { amount: 7500000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.8,
      ratingsCount: 19,
      tags: ['storage', 'credenza', 'sideboard', 'oak', 'scandinavian', 'minimalist'],
      isFeatured: true,
      isBestSeller: false,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Emerald Green Velvet Accent Armchair',
      slug: 'emerald-green-velvet-accent-armchair',
      sku: 'NFI-LIV-004',
      brand: 'National Furniture & Interiors',
      categorySlug: 'living-room',
      description: 'Sculptural silhouette designed for conversational living spaces. Features brushed brass caps on solid tapered legs and ultra-resilient foam cushioning.',
      shortDescription: 'Curved accent armchair in emerald velvet with brass leg caps.',
      material: 'Velvet & Brushed Brass',
      primaryMaterial: 'Velvet Fabric',
      frameMaterial: 'Hardwood & Brass',
      finishes: ['Emerald Velvet', 'Mustard Gold Velvet', 'Charcoal Grey'],
      colors: ['Emerald', 'Gold', 'Charcoal'],
      dimensions: { length: 82, width: 80, height: 85, unit: 'cm' },
      weight: 24,
      careInstructions: 'Spot clean with mild fabric cleaner. Keep away from direct sunlight.',
      warranty: { summary: '3 Years Warranty', periodMonths: 36, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80', publicId: 'armchair-1', isPrimary: true, altText: 'Emerald Accent Armchair' },
        { url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&w=1200&q=80', publicId: 'armchair-2', isPrimary: false, altText: 'Armchair Profile View' },
      ],
      basePrice: { amount: 3800000, currency: 'INR' },
      mrp: { amount: 4800000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.9,
      ratingsCount: 42,
      tags: ['chair', 'armchair', 'velvet', 'living room', 'accent', 'brass'],
      isFeatured: true,
      isBestSeller: true,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Artisanal Solid Rosewood Bedstead',
      slug: 'artisanal-solid-rosewood-bedstead',
      sku: 'NFI-BED-005',
      brand: 'National Furniture & Interiors',
      categorySlug: 'bedroom',
      description: 'Handcrafted Sheesham (Indian Rosewood) king-size bedstead with natural woven rattan cane headboard. Built with traditional mortise-and-tenon joints.',
      shortDescription: 'King-size solid rosewood bed with natural rattan cane headboard.',
      material: 'Solid Rosewood & Cane Weave',
      primaryMaterial: 'Sheesham Rosewood',
      frameMaterial: 'Solid Rosewood',
      finishes: ['Warm Teak Sheen', 'Deep Walnut', 'Raw Matte'],
      colors: ['Rosewood Teak', 'Dark Sheesham'],
      dimensions: { length: 215, width: 195, height: 120, unit: 'cm' },
      weight: 95,
      careInstructions: 'Wipe with soft lint-free cloth. Nourish wood with organic oil every six months.',
      warranty: { summary: '10 Years Termite & Structural Guarantee', periodMonths: 120, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', publicId: 'bed-1', isPrimary: true, altText: 'Solid Rosewood Bedstead' },
        { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80', publicId: 'bed-2', isPrimary: false, altText: 'Woven Headboard Detail' },
      ],
      basePrice: { amount: 14500000, currency: 'INR' },
      mrp: { amount: 18000000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.9,
      ratingsCount: 15,
      tags: ['bed', 'bedroom', 'rosewood', 'king size', 'rattan', 'cane', 'luxury'],
      isFeatured: true,
      isBestSeller: false,
      productType: 'MADE_TO_ORDER',
      status: 'PUBLISHED',
    },
    {
      name: 'Brass & Italian Carrara Marble Coffee Table',
      slug: 'brass-and-italian-carrara-marble-coffee-table',
      sku: 'NFI-LIV-006',
      brand: 'National Furniture & Interiors',
      categorySlug: 'living-room',
      description: 'Honed Italian Carrara marble tabletop resting upon a hand-finished geometric antique brass frame. Sealed against spills with satin nano-coat.',
      shortDescription: 'Round Carrara marble coffee table with geometric brass base.',
      material: 'Carrara Marble & Brushed Brass',
      primaryMaterial: 'Carrara White Marble',
      frameMaterial: 'Solid Brass',
      finishes: ['Carrara White / Antique Brass', 'Nero Marquina / Brushed Gold'],
      colors: ['White Carrara', 'Black Nero'],
      dimensions: { length: 90, width: 90, height: 45, unit: 'cm' },
      weight: 42,
      careInstructions: 'Wipe spills immediately. Use coasters for hot beverage cups.',
      warranty: { summary: '3 Years Warranty', periodMonths: 36, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80', publicId: 'coffee-1', isPrimary: true, altText: 'Marble Coffee Table Overhead' },
        { url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80', publicId: 'coffee-2', isPrimary: false, altText: 'Marble Vein Detail' },
      ],
      basePrice: { amount: 4400000, currency: 'INR' },
      mrp: { amount: 5500000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.7,
      ratingsCount: 28,
      tags: ['coffee table', 'marble', 'brass', 'living room', 'center table'],
      isFeatured: false,
      isBestSeller: true,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Modern Ergonomic Executive Desk',
      slug: 'modern-ergonomic-executive-desk',
      sku: 'NFI-OFF-007',
      brand: 'National Furniture & Interiors',
      categorySlug: 'office',
      description: 'Designed for the modern leader. Solid American walnut desktop with integrated magnetic cable routing channel and leather inlay writing pad.',
      shortDescription: 'Walnut executive desk with integrated cable management.',
      material: 'Solid Walnut Wood & Steel',
      primaryMaterial: 'American Walnut',
      frameMaterial: 'Powder-coated Steel',
      finishes: ['American Walnut', 'Smoked Oak'],
      colors: ['Dark Walnut', 'Espresso'],
      dimensions: { length: 160, width: 80, height: 75, unit: 'cm' },
      weight: 62,
      careInstructions: 'Clean with wood-safe spray and soft cloth. Avoid harsh chemicals.',
      warranty: { summary: '5 Years Commercial Warranty', periodMonths: 60, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80', publicId: 'desk-1', isPrimary: true, altText: 'Executive Desk Studio View' },
        { url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80', publicId: 'desk-2', isPrimary: false, altText: 'Desk Detail with Accessories' },
      ],
      basePrice: { amount: 7200000, currency: 'INR' },
      mrp: { amount: 8800000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.8,
      ratingsCount: 11,
      tags: ['desk', 'office', 'executive', 'walnut', 'work from home', 'ergonomic'],
      isFeatured: false,
      isBestSeller: false,
      productType: 'MADE_TO_ORDER',
      status: 'PUBLISHED',
    },
    {
      name: 'Weathered Teak Outdoor Lounger',
      slug: 'weathered-teak-outdoor-lounger',
      sku: 'NFI-OUT-008',
      brand: 'National Furniture & Interiors',
      categorySlug: 'outdoor',
      description: 'Crafted from sustainable plantation-grown teak high in natural protective oils. 4-position adjustable backrest with Sunbrella all-weather cushions.',
      shortDescription: '4-position teak outdoor chaise lounger with Sunbrella cushion.',
      material: 'Weatherproof Teak Wood',
      primaryMaterial: 'Plantation Teak',
      frameMaterial: 'Solid Teak',
      finishes: ['Weathered Grey Teak', 'Golden Honey Teak'],
      colors: ['Weathered Grey', 'Natural Teak'],
      dimensions: { length: 200, width: 70, height: 35, unit: 'cm' },
      weight: 32,
      careInstructions: 'Teak naturally patinas to silver-grey outdoors. Clean with warm water and soft bristle brush.',
      warranty: { summary: '5 Years Outdoor Durability Warranty', periodMonths: 60, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', publicId: 'outdoor-1', isPrimary: true, altText: 'Outdoor Teak Lounger by Pool' },
        { url: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200&q=80', publicId: 'outdoor-2', isPrimary: false, altText: 'Outdoor Lounger Cushion Close-up' },
      ],
      basePrice: { amount: 3600000, currency: 'INR' },
      mrp: { amount: 4500000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.6,
      ratingsCount: 9,
      tags: ['outdoor', 'lounger', 'teak', 'patio', 'garden', 'weatherproof'],
      isFeatured: false,
      isBestSeller: false,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Handcrafted Teak Sideboard with Fluted Glass',
      slug: 'handcrafted-teak-sideboard-with-fluted-glass',
      sku: 'NFI-DIN-009',
      brand: 'National Furniture & Interiors',
      categorySlug: 'dining',
      description: 'Mid-century inspired buffet credenza featuring fluted reeded glass sliding doors, adjustable interior oak shelving, and integrated tableware drawer dividers.',
      shortDescription: 'Teak dining sideboard with reeded fluted glass doors.',
      material: 'Solid Teak & Fluted Glass',
      primaryMaterial: 'Solid Teak',
      frameMaterial: 'Teak & Fluted Glass',
      finishes: ['Warm Teak', 'Dark Mocha'],
      colors: ['Honey Teak', 'Dark Mocha'],
      dimensions: { length: 165, width: 45, height: 80, unit: 'cm' },
      weight: 68,
      careInstructions: 'Clean glass with vinegar solution; wipe wood with dry cotton cloth.',
      warranty: { summary: '5 Years Warranty', periodMonths: 60, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80', publicId: 'sideboard-1', isPrimary: true, altText: 'Teak Sideboard Dining Room' },
        { url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', publicId: 'sideboard-2', isPrimary: false, altText: 'Fluted Glass Detail' },
      ],
      basePrice: { amount: 5800000, currency: 'INR' },
      mrp: { amount: 7000000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.9,
      ratingsCount: 17,
      tags: ['sideboard', 'dining', 'buffet', 'credenza', 'teak', 'glass'],
      isFeatured: true,
      isBestSeller: false,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Upholstered Linen Dining Chairs (Set of 2)',
      slug: 'upholstered-linen-dining-chairs-pair',
      sku: 'NFI-DIN-010',
      brand: 'National Furniture & Interiors',
      categorySlug: 'dining',
      description: 'Timeless comfort for extended dinner parties. Tailored in Belgian oat linen with curved lumbar support backrest and solid natural oak legs.',
      shortDescription: 'Pair of Belgian linen upholstered dining chairs with solid oak legs.',
      material: 'Belgian Linen & Oak Frame',
      primaryMaterial: 'Belgian Linen',
      frameMaterial: 'Solid Oak',
      finishes: ['Oat Linen / Natural Oak', 'Charcoal Linen / Smoked Oak'],
      colors: ['Oatmeal', 'Slate Charcoal'],
      dimensions: { length: 55, width: 58, height: 84, unit: 'cm' },
      weight: 16,
      careInstructions: 'Vacuum regularly with upholstery nozzle. Fabric protect spray recommended.',
      warranty: { summary: '3 Years Warranty', periodMonths: 36, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', publicId: 'chair-pair-1', isPrimary: true, altText: 'Linen Dining Chairs Pair' },
        { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80', publicId: 'chair-pair-2', isPrimary: false, altText: 'Linen Upholstery Texture' },
      ],
      basePrice: { amount: 2800000, currency: 'INR' },
      mrp: { amount: 3500000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.7,
      ratingsCount: 33,
      tags: ['dining chair', 'dining', 'chairs', 'linen', 'oak', 'pair'],
      isFeatured: false,
      isBestSeller: true,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Fluted Wood Bedside Nightstand',
      slug: 'fluted-wood-bedside-nightstand',
      sku: 'NFI-BED-011',
      brand: 'National Furniture & Interiors',
      categorySlug: 'bedroom',
      description: 'Architectural cylinder nightstand with vertical tambour fluting in solid ash wood. Hidden drawer with antique brass push-to-open latch.',
      shortDescription: 'Cylindrical fluted ash wood bedside table with secret drawer.',
      material: 'Solid Ash Wood & Brass Knob',
      primaryMaterial: 'Solid Ash Wood',
      frameMaterial: 'Ash Wood',
      finishes: ['Natural Bleached Ash', 'Charcoal Stained Ash'],
      colors: ['Bleached Ash', 'Charcoal Ash'],
      dimensions: { length: 45, width: 45, height: 55, unit: 'cm' },
      weight: 18,
      careInstructions: 'Dust with soft dry cloth.',
      warranty: { summary: '3 Years Warranty', periodMonths: 36, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1532323544230-7191fd51bc1b?auto=format&fit=crop&w=1200&q=80', publicId: 'nightstand-1', isPrimary: true, altText: 'Fluted Nightstand by Bed' },
        { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80', publicId: 'nightstand-2', isPrimary: false, altText: 'Fluted Wood Detail' },
      ],
      basePrice: { amount: 1850000, currency: 'INR' },
      mrp: { amount: 2400000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.8,
      ratingsCount: 21,
      tags: ['nightstand', 'bedroom', 'bedside', 'fluted', 'ash wood', 'side table'],
      isFeatured: false,
      isBestSeller: false,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Minimalist Architectural Oak Bookcase',
      slug: 'minimalist-architectural-oak-bookcase',
      sku: 'NFI-OFF-012',
      brand: 'National Furniture & Interiors',
      categorySlug: 'office',
      description: 'Open-concept 5-tier shelving unit celebrating honest structural joinery. Solid European white oak with recessed anti-tip wall anchor hardware.',
      shortDescription: '5-tier open architecture European oak bookcase.',
      material: 'European White Oak',
      primaryMaterial: 'European Oak',
      frameMaterial: 'Solid Oak',
      finishes: ['Natural Matt Oak', 'Smoked Espresso Oak'],
      colors: ['Natural Oak', 'Espresso'],
      dimensions: { length: 110, width: 35, height: 190, unit: 'cm' },
      weight: 54,
      careInstructions: 'Distribute book weight evenly across shelves. Wipe clean with dry cloth.',
      warranty: { summary: '5 Years Structural Warranty', periodMonths: 60, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?auto=format&fit=crop&w=1200&q=80', publicId: 'bookcase-1', isPrimary: true, altText: 'Oak Bookcase with Books & Decor' },
        { url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80', publicId: 'bookcase-2', isPrimary: false, altText: 'Bookcase Shelf Corner Joint' },
      ],
      basePrice: { amount: 4900000, currency: 'INR' },
      mrp: { amount: 6000000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.7,
      ratingsCount: 14,
      tags: ['bookcase', 'shelves', 'storage', 'office', 'oak', 'bookshelf'],
      isFeatured: false,
      isBestSeller: false,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
    {
      name: 'Bespoke 3-Door Solid Wood Wardrobe',
      slug: 'bespoke-3-door-solid-wood-wardrobe',
      sku: 'NFI-BED-013',
      brand: 'National Furniture & Interiors',
      categorySlug: 'bedroom',
      description: 'Grand master wardrobe engineered with handwoven rattan door screens, cedarwood aromatic lining, soft-close hanging rails, and illuminated sensor LED rails.',
      shortDescription: '3-door solid teak & woven rattan wardrobe with cedar interior.',
      material: 'Teak Wood & Natural Rattan',
      primaryMaterial: 'Solid Teak',
      frameMaterial: 'Teak & Natural Cane',
      finishes: ['Warm Teak / Natural Cane', 'Dark Walnut / Honey Cane'],
      colors: ['Teak & Cane', 'Walnut & Cane'],
      dimensions: { length: 180, width: 62, height: 210, unit: 'cm' },
      weight: 140,
      careInstructions: 'Gently vacuum rattan mesh monthly. Wipe teak frame with dry soft flannel.',
      warranty: { summary: '10 Years Comprehensive Warranty', periodMonths: 120, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1200&q=80', publicId: 'wardrobe-1', isPrimary: true, altText: 'Bespoke 3-Door Wardrobe Front' },
        { url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', publicId: 'wardrobe-2', isPrimary: false, altText: 'Rattan Mesh Door Detail' },
      ],
      basePrice: { amount: 16500000, currency: 'INR' },
      mrp: { amount: 21000000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 5.0,
      ratingsCount: 8,
      tags: ['wardrobe', 'bedroom', 'closet', 'almirah', 'teak', 'rattan', 'bespoke'],
      isFeatured: true,
      isBestSeller: false,
      productType: 'MADE_TO_ORDER',
      status: 'PUBLISHED',
    },
    {
      name: 'Mid-Century Swivel Italian Leather Armchair',
      slug: 'mid-century-swivel-italian-leather-armchair',
      sku: 'NFI-OFF-014',
      brand: 'National Furniture & Interiors',
      categorySlug: 'office',
      description: 'Top-grain cognac Italian leather wrapped over an ergonomic curved ply shell with 360-degree silent swivel. Hand-stitched baseball seam perimeter.',
      shortDescription: 'Top-grain Italian leather 360 swivel armchair with aluminum base.',
      material: 'Italian Leather & Cast Aluminum',
      primaryMaterial: 'Italian Full-Grain Leather',
      frameMaterial: 'Bent Walnut Ply & Cast Aluminum',
      finishes: ['Cognac Tan Leather', 'Obsidian Black Leather', 'Vintage Cigar Leather'],
      colors: ['Cognac Tan', 'Black Leather'],
      dimensions: { length: 85, width: 85, height: 95, unit: 'cm' },
      weight: 29,
      careInstructions: 'Condition leather twice a year with organic leather balm. Protect from sharp objects.',
      warranty: { summary: '5 Years Leather & Mechanism Warranty', periodMonths: 60, policyDocumentUrl: '' },
      images: [
        { url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&w=1200&q=80', publicId: 'leather-chair-1', isPrimary: true, altText: 'Cognac Leather Swivel Armchair' },
        { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80', publicId: 'leather-chair-2', isPrimary: false, altText: 'Leather Stitching Detail' },
      ],
      basePrice: { amount: 5200000, currency: 'INR' },
      mrp: { amount: 6500000, currency: 'INR' },
      taxRate: 18,
      taxIncluded: true,
      ratingsAvg: 4.9,
      ratingsCount: 29,
      tags: ['chair', 'office', 'leather', 'armchair', 'swivel', 'italian leather', 'luxury'],
      isFeatured: true,
      isBestSeller: true,
      productType: 'READY_TO_SHIP',
      status: 'PUBLISHED',
    },
  ];

  console.log(`Seeding ${products.length} luxury furniture products...`);

  for (const p of products) {
    const categoryId = categoryMap[p.categorySlug] || categoryMap['living-room'];
    const existing = await db.collection('products').findOne({ sku: p.sku });

    const productDoc = {
      name: p.name,
      slug: p.slug,
      sku: p.sku,
      brand: p.brand,
      categoryId: new mongoose.Types.ObjectId(categoryId),
      categoryIds: [new mongoose.Types.ObjectId(categoryId)],
      description: p.description,
      shortDescription: p.shortDescription,
      material: p.material,
      primaryMaterial: p.primaryMaterial,
      frameMaterial: p.frameMaterial,
      finishes: p.finishes,
      colors: p.colors,
      dimensions: p.dimensions,
      weight: p.weight,
      careInstructions: p.careInstructions,
      warranty: p.warranty,
      images: p.images,
      basePrice: p.basePrice,
      mrp: p.mrp,
      taxRate: p.taxRate,
      taxIncluded: p.taxIncluded,
      ratingsAvg: p.ratingsAvg,
      ratingsCount: p.ratingsCount,
      tags: p.tags,
      isFeatured: p.isFeatured,
      isBestSeller: p.isBestSeller,
      productType: p.productType,
      status: p.status,
      isDeleted: false,
      variants: [
        {
          variantId: new mongoose.Types.ObjectId(),
          sku: `${p.sku}-V1`,
          attributes: [{ name: 'Finish', value: p.finishes[0] }],
          priceOverride: null,
          images: p.images,
          isActive: true,
        },
      ],
      updatedAt: new Date(),
    };

    if (existing) {
      await db.collection('products').updateOne({ _id: existing._id }, { $set: productDoc });
      console.log(`Updated product: ${p.name} (${p.sku})`);
    } else {
      productDoc._id = new mongoose.Types.ObjectId();
      productDoc.createdAt = new Date();
      await db.collection('products').insertOne(productDoc);
      console.log(`Inserted product: ${p.name} (${p.sku})`);
    }
  }

  console.log('Seeding completed successfully!');
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
